#!/bin/bash
apt update -y
apt install apache2 git -y
systemctl start apache2
systemctl enable apache2
systemctl status apache2
cd /var/www/html
rm -f index.html
git clone https://github.com/Ironhack-Archive/online-clone-amazon.git
cp -r online-clone-amazon/* .
chown -R www-data:www-data /var/www/html
chmod -R 755 /var/www/html
systemctl restart apache2
tail -f /var/log/apache2/access.log
